### ISSUE TITLE
dsio-notebook-example.ipynb running abnormally

### ISSUE THREAD

**Issue by tangyong** [MentatInnovations/datastream.io#26]
dsio-notebook-example.ipynb running abnormally

[My env]
1 windows 7 x64
2 python 3.6.2
3 anaconda 3

[Problem]
While I was running dsio-notebook-example.ipynb from jupyter, the following happened,
 
![error1](https://user-images.githubusercontent.com/187414/40168695-b5c001f8-59f6-11e8-8fb7-b954d0759461.png)

**Comment by tangyong** [comment]
duplated with #27

**Comment by litterzhang** [comment]
Did you fix it? I have met the same problem.
